# Generated by Django 5.1.7 on 2025-03-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_batch_batch_name_alter_batch_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracourse',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
